### ISSUE TITLE
HikariConfig and Virtual Threads

### ISSUE THREAD

**Issue by Sineaggi** [mp911de/spring-boot-virtual-threads-experiment#3]
Does Hikari not need to be configured to use virtual threads for it's connection pool? Or does it not matter, due to the currently open HikariCP and PGJDBC virtual-thread issues?

**Comment by mp911de** [comment]
Hikari isn't an `ExecutorService` or the like so it does not host "work". It's your runnable that must run on a Virtual Thread.
